export const authContent = {
  login: {
    title: "Welcome back",
    subtitle: "Sign in to continue to your account",
    emailLabel: "Email Address",
    emailPlaceholder: "you@example.com",
    passwordLabel: "Password",
    passwordPlaceholder: "Enter your password",
    rememberMe: "Remember me",
    forgotPassword: "Forgot password?",
    submitButton: "Sign In",
    submittingButton: "Signing in...",
    dividerText: "Or continue with",
    githubButton: "Continue with GitHub",
    noAccountText: "Don't have an account?",
    signUpLink: "Sign up",
  },
  register: {
    title: "Create your account",
    subtitle: "Join us and start building amazing things",
    nameLabel: "Full Name",
    namePlaceholder: "John Doe",
    emailLabel: "Email Address",
    emailPlaceholder: "you@example.com",
    passwordLabel: "Password",
    passwordPlaceholder: "Create a strong password",
    confirmPasswordLabel: "Confirm Password",
    confirmPasswordPlaceholder: "Confirm your password",
    termsText: "I agree to the",
    termsLink: "Terms of Service",
    andText: "and",
    privacyLink: "Privacy Policy",
    submitButton: "Create Account",
    submittingButton: "Creating account...",
    dividerText: "Or sign up with",
    githubButton: "Continue with GitHub",
    hasAccountText: "Already have an account?",
    signInLink: "Sign in",
  },
  backToHome: "Back to home",
}
