services:
  events:
    container_name: events
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    restart: unless-stopped
    env_file:
      - .env
    environment:
      PORT: "9000"
      PROJECT_DIR: /root/terarush
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/terarush:/root/terarush
      - /root/.ssh:/root/.ssh:ro
    working_dir: /app
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
