services:
  events:
    container_name: events
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    restart: unless-stopped
    environment:
      PORT: "9000"
      PROJECT_DIR: /root/${APP_NAME}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/${APP_NAME}:/root/${APP_NAME}
    working_dir: /app
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
